### ISSUE TITLE
Ingress should work in Kind

### ISSUE THREAD

**Issue by mtp1376** [kuberise/kuberise#23]
`ingress-nginx-controller` is using LoadBalancer. In minikube this is handled well therefore it's working.

But in Kind, probably there's no default ingress controller, so we should use MetalLB to fix the behavior when used in Kind.

**Comment by mojtabaimani** [comment]
Thank you for adding this issue. There is project cloud-provider-kind which solves the problem for kind: https://github.com/kubernetes-sigs/cloud-provider-kind 
I close this issue.
